In [1]:
#numpy for computionoial matrix  speed up
#mat lap for ploting but we didin't used its yet in these  case
#pandas to read the csv in effecint way
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#coz your data is so messy we select only col 1 and 2   and we use tabe as delimiter
dataSet = pd.read_csv('ALL.CSV')#,  sep='\t' , quoting = 3 , usecols=[0,1])
dataSet.head()

الخصخصة سرقه في وضح النهار من الشعب الكهرباء ملك الشعب وليس لحكومة والتجارة بها [[PHOTO]]  \
0  زين المليارات الي انصرفت عليها من سنة ???? لحد...                                          
1                             إلى الجحيم وبئس المصير                                          
2  ولكم ذوله راح ينهبونه رسمي نهبو خيرات  االعراق...                                          
3                             تعبونه  هولاء الحراميه                                          
4  هههههه مي يمتة وداعش تفوق اضعاف قوة البيشمركة ...                                          

     0  
0  0.0  
1  0.0  
2  0.0  
3  0.0  
4  0.0

In [3]:
#these  re use  regx we will use its to keep only arabic letter
import re
data = dataSet.iloc[:,:].values

In [4]:
data[11100,1]

1.0

In [5]:

#here is our preprocessing we take the data the coumint and we split each coumint into words
#then we clean the word
from stop_words import get_stop_words
cs = []
I , J = data.shape
for i in xrange(I):
    dx = str(data[i,0])
    review = re.sub('[\u0627-\u064a]' ,' ' ,dx)
    review = review.split()
    stop_words1=[u'في',u'مثل',u'هاي',u'هذا',u'من',u'ابو',u'مع',u'هم',u'بيهم',u'اللخ',u'هو',u'?']
#get_stop_words('ar')
    stop_words2 = get_stop_words('ar')
    stop_words = stop_words1 + stop_words2
    #these loop remove the stopword from the coumit you can replcat its to make also stem phase
    review = [word for word in review if not unicode(word, encoding='utf-8') in stop_words  ]
    review = ' '.join(review)
    cs.append(review)
#here we do spars matrix  in these we enforce as max 1400 col
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2100)
X = cv.fit_transform(cs).toarray()
y = dataSet.iloc[:, 1].values

for i in xrange(len(y)):
    if np.isnan(y[i]):
        y[i] = 1
        print 1
y

1


array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

In [6]:
X.shape

(11994, 2100)

In [7]:
data[0,0]

'\xd8\xb2\xd9\x8a\xd9\x86 \xd8\xa7\xd9\x84\xd9\x85\xd9\x84\xd9\x8a\xd8\xa7\xd8\xb1\xd8\xa7\xd8\xaa \xd8\xa7\xd9\x84\xd9\x8a \xd8\xa7\xd9\x86\xd8\xb5\xd8\xb1\xd9\x81\xd8\xaa \xd8\xb9\xd9\x84\xd9\x8a\xd9\x87\xd8\xa7 \xd9\x85\xd9\x86 \xd8\xb3\xd9\x86\xd8\xa9 ???? \xd9\x84\xd8\xad\xd8\xaf ???? \xd9\x88\xd9\x8a\xd9\x86\xd9\x87\xd8\xa7 \xd9\x87\xd8\xb0\xd9\x86\xd9\x8a\xd8\xac \xd9\x86\xd8\xb2\xd9\x84\xd8\xaa\xd9\x88\xd9\x87\xd8\xa7 \xd8\xa8\xd8\xac\xd9\x8a\xd8\xa8\xd9\x88\xd9\x83\xd9\x85 \xd9\x83\xd9\x84\xd9\x83\xd9\x85 \xd8\xad\xd8\xb1\xd8\xa7\xd9\x85\xd9\x8a\xd9\x87 \xd9\x88\xd9\x84\xd8\xa7 \xd9\x88\xd8\xa7\xd8\xad\xd8\xaf \xd8\xb4\xd8\xb1\xd9\x8a\xd9\x81 \xd8\xa8\xd9\x8a\xd9\x83\xd9\x85'

In [8]:
print unicode(cs[11], encoding='utf-8')

سارق اموال النازحين


In [9]:
print unicode(data[11,0], encoding='utf-8')

سارق اموال النازحين


In [10]:
print X[4]

[0 0 0 ..., 0 0 0]


In [11]:
#split data for training and test  but in our case its so bad to do so coz we have very very litile data
#please increase the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)


In [ ]:
#gradaint boost treee is learning like neural networks
from sklearn.ensemble import GradientBoostingClassifier

classifier = GradientBoostingClassifier(n_estimators=500, learning_rate=1.0,max_depth=5, random_state=0, n_jobs=-1)


In [ ]:
#adaboost  bosted ensamble learning
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(n_estimators=500)
                                        



In [ ]:
from sklearn.model_selection import cross_val_score
classifier = classifier.fit(X_train , y_train)
scores = cross_val_score(classifier, X_train , y_train, cv=5)
print scores
plt.plot(scores)
plt.show()

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))


In [12]:
#التصنيف بتقنية التصويت  مطولة ولكن  مفيدة
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB

clf0 = AdaBoostClassifier(n_estimators=300)

# Training classifiers
clf1 = DecisionTreeClassifier(max_depth=36)
clf2 = KNeighborsClassifier(n_neighbors=12)
clf3 = SVC(kernel='rbf', probability=True)

clf4 = GaussianNB()
classifier = VotingClassifier(estimators=[('ada',clf0),('dt', clf1), ('knn', clf2), ('svc', clf3) ,('navia' , clf4)], voting='soft',n_jobs=-1, weights=[3,2,2,1,1])


classifier = classifier.fit(X_train , y_train)

In [13]:
y_pred = classifier.predict(X_test)
y_pred

array([ 1.,  0.,  1., ...,  0.,  1.,  0.])

In [14]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [15]:
cm

array([[1874,  141],
       [ 292, 1292]])

In [16]:
def getscore(orgin , predicted):
    score = 0
    print orgin.shape
    #print score
    j = 0
    for i in predicted:
        if i == orgin[j]:
            score +=1
            j +=1
        else:
            #score -=1
            j +=1
    print score
    result = (score / float(orgin.shape[0]) ) * 100.00000
    result = str(result)
    return result+'%'

In [17]:
getscore(y_test,y_pred)

(3599,)
3166


'87.9688802445%'

In [18]:
SCORS = np.mean(y_test == y_pred)
print SCORS

0.879688802445
